version: '3'

services:
  flutter-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"  # Adjust the port as needed
    volumes:
      - .:/app
    environment:
      PUB_HOSTED_URL: https://pub.flutter-io.cn
      FLUTTER_STORAGE_BASE_URL: https://storage.flutter-io.cn
